name = "InfiniteTensorContractions"
uuid = "742c4823-a45f-4b1c-bad3-1a5bdcda2a0b"
authors = ["jack-dunham <ucapunh@ucl.ac.uk>"]
version = "0.1.0"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
DocStringExtensions = "0.9.3"
TensorKit = "0.14.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Test", "TestSetExtensions"]
