name = "InfiniteTensorContractions"
uuid = "742c4823-a45f-4b1c-bad3-1a5bdcda2a0b"
authors = ["jack-dunham <ucapunh@ucl.ac.uk>"]
version = "0.1.0"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
KrylovKit = "<0.8.2"
TensorKit = "=0.12.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"

[targets]
test = ["Test", "TestExtras"]
